version: "3.9"

services:
  jobmanager:
    image: flink:1.18-scala_2.12-java11
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    ports:
      - "8081:8081"          # Flink Web & REST

  taskmanager:
    image: flink:1.18-scala_2.12-java11
    command: taskmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
      - TASK_MANAGER_NUMBER_OF_TASK_SLOTS=2
    depends_on: [jobmanager]